### PR TITLE
fix: fix coverage 422 error and release error

### PR DESCRIPTION
**Pull request by Nekotoxin**

### CODE REVIEW

**Comment by Nekotoxin** [comment]
@leeqvip Can you teach me how to solve the coveralls error problem?

**Comment by leeqvip** [comment]
@Nekotoxin Did you try to restore it to a previous version?

**Comment by Nekotoxin** [comment]
> @Nekotoxin Did you try to restore it to a previous version?

no, the previous version is also 422 error, tried many times.

**Comment by leeqvip** [comment]
it has been fixed in this PR#11

**Pull request closed without merging**
